import type { BudgetTableRow, BudgetUnitNode, FilterSnapshot } from '@/types/budget'

export const memoryStorageKey = 'budget-unit-demo-memory'

export const defaultMemorySnapshot: FilterSnapshot = {
  selectedIds: ['30011', '300112'],
  filterToTopLevel: false,
  showPermittedOnly: true,
}

export const budgetTree: BudgetUnitNode[] = [
  {
    id: '10000',
    name: '智能语音交互',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
    children: [
      {
        id: '30011',
        name: '扣子',
        parentId: '10000',
        level: 2,
        hasPermission: true,
        status: 'active',
        children: [
          {
            id: '300111',
            name: '扣子(子项A)',
            parentId: '30011',
            level: 3,
            hasPermission: true,
            status: 'active',
          },
          {
            id: '300112',
            name: '扣子(子项B)',
            parentId: '30011',
            level: 3,
            hasPermission: false,
            status: 'active',
          },
        ],
      },
      {
        id: '10012',
        name: '豆包大模型',
        parentId: '10000',
        level: 2,
        hasPermission: false,
        status: 'expired',
      },
      {
        id: '10013',
        name: '豆包大模型',
        parentId: '10000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '10014',
        name: '隐私计算平台',
        parentId: '10000',
        level: 2,
        hasPermission: true,
        status: 'expired',
      },
    ],
  },
  {
    id: '11000',
    name: '行业PaaS',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
  },
  {
    id: '12000',
    name: 'CDN与加速',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
  },
  {
    id: '13000',
    name: '基础深度学习',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
  },
  {
    id: '14000',
    name: 'Bot 平台',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
  },
  {
    id: '15000',
    name: '终端智能配备',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
  },
  {
    id: '16000',
    name: '小说',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
  },
  {
    id: '17000',
    name: '财经',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
    children: [
      {
        id: '17011',
        name: '证券',
        parentId: '17000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '17012',
        name: '保险',
        parentId: '17000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '17013',
        name: '支付',
        parentId: '17000',
        level: 2,
        hasPermission: false,
        status: 'active',
      },
      {
        id: '17014',
        name: '消费金融',
        parentId: '17000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '17015',
        name: '财经公共',
        parentId: '17000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
    ],
  },
  {
    id: '18000',
    name: '生态',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
    children: [
      {
        id: '18011',
        name: '生态抖店产品',
        parentId: '18000',
        level: 2,
        hasPermission: true,
        status: 'expired',
      },
      {
        id: '18012',
        name: '生态抖店产品',
        parentId: '18000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '18013',
        name: '云市场生态产品',
        parentId: '18000',
        level: 2,
        hasPermission: false,
        status: 'expired',
      },
      {
        id: '18014',
        name: '云市场生态产品',
        parentId: '18000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '18015',
        name: '零信任安全一体机',
        parentId: '18000',
        level: 2,
        hasPermission: false,
        status: 'expired',
      },
    ],
  },
  {
    id: '19000',
    name: '汽车',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
    children: [
      {
        id: '19011',
        name: '后座屏',
        parentId: '19000',
        level: 2,
        hasPermission: true,
        status: 'expired',
      },
      {
        id: '19012',
        name: '火山车娱',
        parentId: '19000',
        level: 2,
        hasPermission: false,
        status: 'expired',
      },
      {
        id: '19013',
        name: '场景智能',
        parentId: '19000',
        level: 2,
        hasPermission: true,
        status: 'expired',
      },
      {
        id: '19014',
        name: '火山车娱',
        parentId: '19000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '19015',
        name: '场景智能',
        parentId: '19000',
        level: 2,
        hasPermission: false,
        status: 'active',
      },
    ],
  },
  {
    id: '20000',
    name: '飞连',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
    children: [
      {
        id: '20011',
        name: '飞连一体机',
        parentId: '20000',
        level: 2,
        hasPermission: true,
        status: 'expired',
      },
      {
        id: '20012',
        name: '飞连 私有化版',
        parentId: '20000',
        level: 2,
        hasPermission: false,
        status: 'expired',
      },
      {
        id: '20013',
        name: '飞连 公有云版',
        parentId: '20000',
        level: 2,
        hasPermission: true,
        status: 'expired',
      },
      {
        id: '20014',
        name: '飞连 公有云版',
        parentId: '20000',
        level: 2,
        hasPermission: true,
        status: 'active',
        children: [
          {
            id: '200141',
            name: '飞连智能体',
            parentId: '20014',
            level: 3,
            hasPermission: true,
            status: 'active',
          },
          {
            id: '200142',
            name: '飞连公有云版',
            parentId: '20014',
            level: 3,
            hasPermission: true,
            status: 'active',
          },
          {
            id: '200143',
            name: '飞连公有云版跨域服务',
            parentId: '20014',
            level: 3,
            hasPermission: false,
            status: 'active',
          },
        ],
      },
      {
        id: '20015',
        name: '飞连 私有化版',
        parentId: '20000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '20016',
        name: '飞连-Base校准',
        parentId: '20000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '20017',
        name: '火山引擎-飞连打包成本',
        parentId: '20000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '20018',
        name: '火山引擎-飞连打包收入',
        parentId: '20000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
    ],
  },
  {
    id: '21000',
    name: '推荐',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
    children: [
      {
        id: '21011',
        name: '智能创意',
        parentId: '21000',
        level: 2,
        hasPermission: false,
        status: 'expired',
      },
      {
        id: '21012',
        name: '广告内容理解',
        parentId: '21000',
        level: 2,
        hasPermission: true,
        status: 'expired',
      },
      {
        id: '21013',
        name: '广告创意工具',
        parentId: '21000',
        level: 2,
        hasPermission: false,
        status: 'expired',
      },
      {
        id: '21014',
        name: 'AI搜索引擎',
        parentId: '21000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '21015',
        name: '程序化创意算法',
        parentId: '21000',
        level: 2,
        hasPermission: true,
        status: 'expired',
      },
    ],
  },
  {
    id: '22000',
    name: '存储',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
  },
  {
    id: '23000',
    name: '计算',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
    children: [
      {
        id: '23011',
        name: '持续交付',
        parentId: '23000',
        level: 2,
        hasPermission: true,
        status: 'active',
        children: [
          {
            id: '230111',
            name: '持续交付',
            parentId: '23011',
            level: 3,
            hasPermission: true,
            status: 'active',
          },
          {
            id: '230112',
            name: '持续交付-自动驾驶云',
            parentId: '23011',
            level: 3,
            hasPermission: false,
            status: 'active',
          },
        ],
      },
      {
        id: '23012',
        name: '镜像仓库',
        parentId: '23000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '23013',
        name: '弹性容器',
        parentId: '23000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '23014',
        name: '镜像服务',
        parentId: '23000',
        level: 2,
        hasPermission: false,
        status: 'active',
      },
      {
        id: '23015',
        name: '云服务器',
        parentId: '23000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
      {
        id: '23016',
        name: '飞连',
        parentId: '23000',
        level: 2,
        hasPermission: true,
        status: 'active',
      },
    ],
  },
  {
    id: '24000',
    name: '网络',
    parentId: null,
    level: 1,
    hasPermission: true,
    status: 'active',
  },
]

export const budgetTableRows: BudgetTableRow[] = [
  {
    rowId: 'row-01',
    budgetUnitId: '10000',
    budgetUnitName: '智能语音交互',
    project: '语音助手全球化',
    owner: '周悦',
    costCenter: 'CC-VOICE-01',
    monthlyBudget: 520000,
    updatedAt: '2026-06-20',
  },
  {
    rowId: 'row-02',
    budgetUnitId: '30011',
    budgetUnitName: '扣子',
    project: '智能体模板工厂',
    owner: '刘昊',
    costCenter: 'CC-COZE-01',
    monthlyBudget: 280000,
    updatedAt: '2026-06-18',
  },
  {
    rowId: 'row-03',
    budgetUnitId: '300111',
    budgetUnitName: '扣子(子项A)',
    project: '企业知识库问答',
    owner: '何远',
    costCenter: 'CC-COZE-12',
    monthlyBudget: 410000,
    updatedAt: '2026-06-17',
  },
  {
    rowId: 'row-04',
    budgetUnitId: '16000',
    budgetUnitName: '小说',
    project: '内容运营提效',
    owner: '李晴',
    costCenter: 'CC-NOVEL-02',
    monthlyBudget: 190000,
    updatedAt: '2026-06-13',
  },
  {
    rowId: 'row-05',
    budgetUnitId: '17011',
    budgetUnitName: '证券',
    project: '行情分析增强',
    owner: '陈舟',
    costCenter: 'CC-FIN-08',
    monthlyBudget: 360000,
    updatedAt: '2026-06-19',
  },
  {
    rowId: 'row-06',
    budgetUnitId: '18014',
    budgetUnitName: '云市场生态产品',
    project: '渠道生态增长',
    owner: '许然',
    costCenter: 'CC-ECO-12',
    monthlyBudget: 128000,
    updatedAt: '2026-06-22',
  },
  {
    rowId: 'row-07',
    budgetUnitId: '19014',
    budgetUnitName: '火山车娱',
    project: '车载娱乐升级',
    owner: '林清',
    costCenter: 'CC-AUTO-15',
    monthlyBudget: 96000,
    updatedAt: '2026-06-11',
  },
  {
    rowId: 'row-08',
    budgetUnitId: '20014',
    budgetUnitName: '飞连 公有云版',
    project: '统一安全接入平台',
    owner: '魏川',
    costCenter: 'CC-FL-21',
    monthlyBudget: 630000,
    updatedAt: '2026-06-09',
  },
  {
    rowId: 'row-09',
    budgetUnitId: '200141',
    budgetUnitName: '飞连智能体',
    project: '智能策略编排',
    owner: '章序',
    costCenter: 'CC-FL-18',
    monthlyBudget: 215000,
    updatedAt: '2026-06-21',
  },
  {
    rowId: 'row-10',
    budgetUnitId: '21014',
    budgetUnitName: 'AI搜索引擎',
    project: '广告推荐召回优化',
    owner: '韩隽',
    costCenter: 'CC-REC-09',
    monthlyBudget: 248000,
    updatedAt: '2026-06-23',
  },
  {
    rowId: 'row-11',
    budgetUnitId: '23011',
    budgetUnitName: '持续交付',
    project: '研发流水线统一治理',
    owner: '宋岚',
    costCenter: 'CC-CAL-05',
    monthlyBudget: 332000,
    updatedAt: '2026-06-16',
  },
  {
    rowId: 'row-12',
    budgetUnitId: '230111',
    budgetUnitName: '持续交付',
    project: '发布质量基线建设',
    owner: '江策',
    costCenter: 'CC-CAL-11',
    monthlyBudget: 176000,
    updatedAt: '2026-06-08',
  },
  {
    rowId: 'row-13',
    budgetUnitId: '23015',
    budgetUnitName: '云服务器',
    project: '弹性资源池优化',
    owner: '唐恪',
    costCenter: 'CC-CAL-19',
    monthlyBudget: 289000,
    updatedAt: '2026-06-12',
  },
  {
    rowId: 'row-14',
    budgetUnitId: '23016',
    budgetUnitName: '飞连',
    project: '计算资源接入治理',
    owner: '顾行',
    costCenter: 'CC-CAL-23',
    monthlyBudget: 198000,
    updatedAt: '2026-06-23',
  },
]
